### ISSUE TITLE
local demo running issue

### ISSUE THREAD

**Issue by yypurpose** [rese1f/MovieChat#13]
There are some problems when I try to run the local demo:
1. Missing "src/examples/Cooking_cake.mp4" metioned in README
2. In Line 373 of inference.py (https://github.com/rese1f/MovieChat/blob/main/inference.py#L373), middle_video is set True, so what's the point of setting it to 0 in args mentioned in README? How to run the model in the global mode?

THX!

**Comment by yypurpose** [comment]
and
1. why is the function gener_infer in Chat is not used.
2. what's the difference between fragment-video-path and video-path, why a fragment-video-path is needed?

**Comment by Espere-1119-Song** [comment]
1. Since GitHub does not support the upload of too large long movies ( > 40M), we did not give specific examples. You can choose any video to replace.
2. When middle_video is set to true or 1, it represents breakpoint mode; when middle_video is set to false or 0, it represents global mode.
3. Function gener_infer will be used in gradio demo.
4. video-path refers to the path of the complete movie, and fragment-video-path represents the short video temporarily stored at each step when the sliding window reads the video.

**Comment by yypurpose** [comment]
thank you for your reply. It makes me clear with 1 & 4, but I'm still a little bit confused about 2 & 3.
for Q2, I mean the code forces middle_video to be True, which makes args.middle_video no sense (**as no matter which value is set to  args.middle_video, middle_video is always True**), is it a mistake? or you can figure me out the problem.
for Q3, it seems gradio demo **does not** import any function from inference.py.

THX!
