### ISSUE TITLE
Frame-aware?

### ISSUE THREAD

**Issue by jayavanth** [rese1f/MovieChat#40]
Hello! I wanted to know if this model is frame aware? Can I ask questions like "when does the person wearing yellow jacket appear in this video?" Doesn't seem like models like VideoChat can do it based on demos on huggingface but in the paper I saw a figure where Video-Llama could say which frame it occurred in.  Is MovieChat able to do that?

**Comment by Espere-1119-Song** [comment]
Thank you for your insterest. 

MovieChat uses a video Q-Former to encode temporal information. If you ask questions like "when does the person wearing yellow jacket appear in this video?", the answer you will probably get is "It appears after ....( something happen)". We found in the experiment that although MovieChat may give frame aware answers (see Figure F2 in paper for details), it is not accurate enough. This is because no specific time information is involved during the training process.

In addition, MovieChat uses Video-LLaMA as its base model, but I checked the Video-LLaMA paper and did not find the frame aware example you mentioned. Can you share a screenshot with me?

**Comment by jayavanth** [comment]
Thanks Enxin! This is the example where Video-Llama references the frame number

![Screenshot 2024-02-06 at 10 23 02 AM](https://github.com/rese1f/MovieChat/assets/584402/4c540a2a-221f-4a61-a93e-fe0671c4af13)

**Comment by Espere-1119-Song** [comment]
Thanks for your support. Referring to the structure of Video-Llama, I think it gives such an answer just by chance.

**Comment by jayavanth** [comment]
I see. Thank  you!
